### ISSUE TITLE
Dependabot now can handle cocoapods?

### ISSUE THREAD

**Issue by ansereb** [advanced-security/cocoapods-dependency-submission-action#3]
Hi @GeekMasher!

In readme you mentioned than "Dependabot can use the CocoaPods to check for security vulnerabilities". Does it means that dependabot now have official support of cocoapods vulnerability feed? It haven't before https://github.com/dependabot/dependabot-core/issues/416

**Comment by GeekMasher** [comment]
@ansereb This is a GitHub Action that will process `Podfile.lock` files and submit them to the Dependency Graph

![image](https://github.com/advanced-security/cocoapods-dependency-submission-action/assets/2772944/08d2897d-e033-456a-8c49-03d9a14d91e8)

Right now, the [Advisory Database does support Swift packages](https://github.com/advisories?query=type%3Areviewed+ecosystem%3Aswift) so you should be able to see security issues from CocoaPods files.

You might have to wait until #4 is merged tho.

**Comment by ansereb** [comment]
Thanks for informing! Looking forward to work with this action

**Comment by ansf** [comment]
Do you know if it still is the case that the Github Advisory Database does not contain Swift packages? Now your link points to some swift advisories: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Aswift

But I am not sure, if they would match CocoaPods dependencies, or only Swift Package Manager dependencies.
